### PR TITLE
Increase package version (v0.1.42)

### PR DESCRIPTION
**Pull request by s-ol**
See assemblee-virtuelle/semapps#508.

Implements breaking changes from semapps PRs:
- assemblee-virtuelle/semapps#492
- assemblee-virtuelle/semapps#539

### CODE REVIEW

**Review by srosset81 — CHANGES_REQUESTED** [review]
There is one thing missing: since https://github.com/assemblee-virtuelle/semapps/pull/492, the ActivityPub containers for actors and objects are now handled through the `ldp` service (except /activities which is a special container). So you need to load them, for example like this:

```js
const { LdpService } = require('@semapps/ldp');
const { containers } = require('@semapps/activitypub');

module.exports = {
  mixins: [LdpService],
  settings: {
    baseUrl: process.env.SEMAPPS_HOME_URL,
    containers
  }
};
```

I will add this to the documentation.

**Comment by srosset81** [comment]
Here's the updated documentation: https://github.com/assemblee-virtuelle/semapps/commit/3d45b0353da3b2883425c82f29b863e6728c8e2b

**Comment by s-ol** [comment]
Ok, I also split this PR into multiple commits like the other one.

**Review by srosset81 — APPROVED** [review]
Nice ! Thanks again.
I merge so that the new template can be used immediately. @sauvagemathilde I will let you check that everything works fine.

**Pull request merged**
